### ISSUE TITLE
필수 기능 연습

### ISSUE THREAD

**Issue by unam98** [UKi-Client/iOS#1]
## 💡 Issue

실질적인 개발 기간이 짧으므로 필수 기능 구현을 미리 해보아야 합니다!

## 📝 todo

- [ ] Firebase에 직접 data 추가해보기 
- [ ] 한 data의 모든 속성 받아오기 (ex. 한 data가 'name, 'ImageUrl', 'address'라는 속성을 가지고 있다면 이 모두를 한 번에 받아오기)
- [ ] 한 data에서 특정 속성만 받아오기 (ex. 한 data에서 'name'만 받아오기)
- [ ] 받아온 data를 테이블 뷰에 바인딩 해보기 (이미지, text 둘 다)
- [ ] 바텀네비게이션바 구현 (각 menu 터치 시 페이지 전환, 아이콘 색상 변경까지)
- [ ] 웹뷰 구현 (iOS 앱에서 외부 웹사이트를 띄울 수 있는 것)
- [ ] 테이블 뷰 item 터치 시 상세페이지로 이동 및 data 전달 (가령 '서울 보호소'를 터치하면 서울 보호소 data가 상세페이지로 전달될 수 있게 해야 함.)
